### ISSUE TITLE
Can't find react in registry when run as prepare script

### ISSUE THREAD

**Issue by dkreft** [alexindigo/install-peers-cli#11]
When I execute `yarn install`, I see this:

```
.
.
.
$ install-peers
- Installing 2 peerDependencies...
Unable to install peerDependencies Error: Command failed: "/Users/dkreft/.nvm/versions/node/v12.18.4/bin/node" "/usr/local/Cellar/yarn/1.22.10/libexec/bin/yarn.js" add  --peer --pure-lockfile "react@^16.9" "react-dom@^16.9"
error Couldn't find package "react" on the "npm" registry.
    at ChildProcess.exithandler (child_process.js:303:12)
    at ChildProcess.emit (events.js:315:20)
    at maybeClose (internal/child_process.js:1021:16)
    at Socket.<anonymous> (internal/child_process.js:443:11)
    at Socket.emit (events.js:315:20)
    at Pipe.<anonymous> (net.js:674:12) {
  killed: false,
  code: 1,
  signal: null,
  cmd: '"/Users/dkreft/.nvm/versions/node/v12.18.4/bin/node" "/usr/local/Cellar/yarn/1.22.10/libexec/bin/yarn.js" add  --peer --pure-lockfile "react@^16.9" "react-dom@^16.9"',
  stdout: 'yarn add v1.22.10\n' +
    '[1/4] Resolving packages...\n' +
    'info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.',
  stderr: `error Couldn't find package "react" on the "npm" registry.`
}
verbose 1.392749916 Error: Command failed with exit code 1.
    at ProcessTermError.ExtendableBuiltin (/usr/local/Cellar/yarn/1.22.10/libexec/lib/cli.js:721:66)
    at ProcessTermError.MessageError (/usr/local/Cellar/yarn/1.22.10/libexec/lib/cli.js:750:123)
    at new ProcessTermError (/usr/local/Cellar/yarn/1.22.10/libexec/lib/cli.js:790:113)
    at /usr/local/Cellar/yarn/1.22.10/libexec/lib/cli.js:34550:30
    at Generator.throw (<anonymous>)
    at step (/usr/local/Cellar/yarn/1.22.10/libexec/lib/cli.js:310:30)
    at /usr/local/Cellar/yarn/1.22.10/libexec/lib/cli.js:323:13
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
error Command failed with exit code 1.

```

Yet when I run the command manually, it works just fine:

```
% /Users/dkreft/.nvm/versions/node/v12.18.4/bin/node "/usr/local/Cellar/yarn/1.22.10/libexec/bin/yarn.js" add  --peer --pure-lockfile "react@^16.9" "react-dom@^16.9"
yarn add v1.22.10
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
[4/4] 🔨  Building fresh packages...
success Saved 2 new dependencies.
info Direct dependencies
├─ react-dom@16.14.0
└─ react@16.14.0
info All dependencies
├─ react-dom@16.14.0
└─ react@16.14.0
$ install-peers
Only run install-peer-deps after `install` command. Skipping.
✨  Done in 2.83s.
```

I *do* have an `~/.npmrc`...could it be that your script isn't honoring it?

```sh
@myscope:registry=https://npm.pkg.github.com/
registry=https://registry.npmjs.org/
//npm.pkg.github.com/:_authToken=REDACTED_TOKEN
```

Here's the diff of my `package.json`:

```jdiff
diff --git a/package.json b/package.json
index 9d888fb..9497b9f 100644
--- a/package.json
+++ b/package.json
@@ -31,12 +31,11 @@
     "eslint-plugin-react-perf": "^3.3.0",
     "husky": "^4.3.6",
     "identity-obj-proxy": "^3.0.0",
+    "install-peers-cli": "^2.2.0",
     "jest": "^26.6.3",
     "jest-enzyme": "^7.1.2",
     "process": "^0.11.10",
     "prop-types": "^15.7.2",
-    "react": "16.9",
-    "react-dom": "16.9",
     "react-styleguidist": "^11.1.5",
     "sass": "^1.30.0",
     "sass-loader": "^10.1.0",
@@ -45,7 +44,8 @@
     "webpack-cli": "^4.2.0"
   },
   "peerDependencies": {
-    "react": "^16.9"
+    "react": "^16.9",
+    "react-dom": "^16.9"
   },
   "scripts": {
     "build": "webpack --mode production",
@@ -54,7 +54,8 @@
     "build:styleguide": "styleguidist build",
     "lint": "eslint src *.js .*.js --ext .js,.jsx",
     "test": "jest --watch",
-    "test:coverage": "jest --no-cache --coverage"
+    "test:coverage": "jest --no-cache --coverage",
+    "prepare": "install-peers"
   },
   "husky": {
     "hooks": {
```

**Comment by rewdy** [comment]
FWIW, I'm having the same problem... custom registry being ignored even though it's set in my ~/.npmrc and my project-specific .npmrc file.

**Comment by vskh** [comment]
If anyone else stumbles across the issue where install-peers seems to ignore the .npmrc configuration, here is what I found.

I use yarn and I run install-peers as 'prepare' script  in my package.json (this way it runs after each install). Install-peers internally also calls package manager to add those peer dependencies, and yarn (in my case) does scan and discover all the configs just like when you run it from command like directly (proved this by adding `--verbose` flag to yarn invocation in install-peers source code), however, the environment which that child yarn is invoked is different. Since it's run from the script, yarn provides whole bunch of environment mimicking NPM to it which instance of yarn started from install-peers picks up. The culprit is `npm_config_registry` which in my case is being set to regular a npmjs registry thus none of my private packages can be found.

The solution I came up with is simple - unset the `npm_config_registry` environment variable before calling install-peers in prepare script. I.e. `"prepare": "unset npm_config_registry && install-peers"` (will only work in *NIX/WSL). I needed it to work cross-OS (to work both on *NIX and Windows) so ended up with js script that unsets `process.env['npm_config_registry']` before running the command.

Not sure about the reason of such behavior in yarn but hope this would help.
